// this action types are used for consuming a REST api.
export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_REJECT = 'REQUEST_USER_REJECT';

export const SAVE_LOGGED_VENDOR = 'SAVE_LOGGED_VENDOR';
export const UPDATE_LOGGED_VENDOR = 'UPDATE_LOGGED_VENDOR';
export const UPDATE_LOGGED_VENDOR_VERIFIED = 'UPDATE_LOGGED_VENDOR_VERIFIED';
export const UPDATE_LOGGED_VENDOR_TOKEN = 'UPDATE_LOGGED_VENDOR_TOKEN';
export const UPDATE_LOGGED_VENDOR_JWT = 'UPDATE_LOGGED_VENDOR_JWT';
export const DESTROY_LOGGED_VENDOR = 'DESTROY_LOGGED_VENDOR';

export const REQUEST_VENDOR_PENDING = 'REQUEST_VENDOR_PENDING';
export const REQUEST_VENDOR_SUCCESS = 'REQUEST_VENDOR_SUCCESS';
export const REQUEST_VENDOR_REJECT = 'REQUEST_VENDOR_REJECT';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
